name: flutter_clean_architecture_posts_app
description: Learning clean architecture with bloc   .
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  get_it: ^7.6.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true